### ISSUE TITLE
info.json spec/doc is missing

### ISSUE THREAD

**Issue by duk3luk3** [Brutus5000/BiReUS#1]
there's no information about what info.json needs to look like (except in the test data script)

**Comment by Brutus5000** [comment]
Yes. Unfortunately the contents of info.json are different in client & server. As of now it's just a key/value-store for information about the whole repository status.

I haven't found the optimal solution yet. Probably, the .versions-file will also be merged into the servers info.json.

**Comment by Brutus5000** [comment]
Now documented in [wiki](https://github.com/Brutus5000/BiReUS/wiki)
